events {}

http {
    upstream lumie_client {
        server client:8501;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://lumie_client;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
